name: Continuous Integration + Continuous development using vercel

on:
  pull_request: 
    branches: 
      - main

jobs: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: nd1fnzdBPeeoLCpKmo2tPhmz
          vercel-org-id: team_kNQtVXUdakavZum8CGoC2X0e
          vercel-project-id: prj_4QrpXessFc7JzYLFNYQDgJepJzRY
          working-directory: ./
